swagger: "2.0"
info:
  version: "1.0.0"
  title: FoodList API
host: localhost:8081
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /foods:
    get:
      tags:
        - foods
      description: Returns Food List to the user
      operationId: food
      parameters:
        - name: page
          in: query
          description: The number of current page
          required: false
          type: string
        - name: limit
          in: query
          description: The limit number of ocurrences that must be showed per page
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ingredientsDefinition"
    post:
      tags:
        - foods
      description: Submit an new Food to the list
      operationId: food
      parameters:
        - in: body
          name: postFoodPayload
          description: Payload format to submit an new food
          schema:
            type: object
            required:
              - refillable
              - drinkable
              - name
              - price
            properties:
              refillable:
                type: boolean
              drinkable:
                type: boolean
              name:
                type: string
              price:
                type: number
              size:
                type: string
              spicy:
                type: string
              ingredients:
                type: array
                items:
                  $ref: "#/definitions/ingredientsDefinition"
            example:
              name: "Burrito"
              refillable: true
              drinkable: false
              price: 2.17
              size: "P"
              spicy: "Hot"
              ingredients:
                - name: "Lettuce"
                  isExpired: false
                - name: "Onions"
                  isExpired: false
                - name: "Meat"
                  isExpired: false
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UndefinedYetResponse"
        "400":
          description: BadRequest
          schema:
            $ref: "#/definitions/BadRequest"
  /foods/{foodId}:
    get:
      tags:
        - foodById
      description: Returns exclusive food by id
      operationId: food
      parameters:
        - name: foodId
          in: path
          required: true
          type: string
          description: ID of the current Food
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/foodItem"
        "404":
          description: Resouce not found
          schema:
            $ref: "#/definitions/NotFound"
    put:
      tags:
        - foodById
      description: Edit informations from an specific Food
      operationId: food
      parameters:
        - name: foodId
          in: path
          required: true
          type: string
          description: ID of the current Food
        - in: body
          name: putFoodPayload
          description: Payload format to edit the current Food
          schema:
            type: object
            properties:
              refillable:
                type: boolean
              drinkable:
                type: boolean
              name:
                type: string
              price:
                type: number
              size:
                type: string
              spicy:
                type: string
              ingredients:
                type: array
                items:
                  $ref: "#/definitions/ingredientsDefinition"
            example:
              name: "Burrito"
              refillable: true
              drinkable: false
              price: 2.17
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UndefinedYetResponse"
        "404":
          description: Resouce not found
          schema:
            $ref: "#/definitions/NotFound"
    patch:
      tags:
        - foodById
      description: Edit only one atribute from an specific Food
      operationId: food
      parameters:
        - name: foodId
          in: path
          required: true
          type: string
          description: ID of the current Food
        - in: body
          name: patchFoodPayload
          description: Payload format to edit the current Food
          schema:
            type: object
            properties:
              refillable:
                type: boolean
              drinkable:
                type: boolean
              name:
                type: string
              price:
                type: number
              size:
                type: string
              spicy:
                type: string
              ingredients:
                type: array
                items:
                  $ref: "#/definitions/ingredientsDefinition"
            example:
              name: "Burrito Patched"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UndefinedYetResponse"
        "404":
          description: Resouce not found
          schema:
            $ref: "#/definitions/NotFound"
    delete:
      tags:
        - foodById
      description: Remove the specific food from Food List
      operationId: food
      parameters:
        - name: foodId
          in: path
          required: true
          type: string
          description: ID of the current Food
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UndefinedYetResponse"
        "404":
          description: Resouce not found
          schema:
            $ref: "#/definitions/NotFound"
  /combos:
    get:
      tags:
        - combos
      description: Returns Combo List to the user
      operationId: combo
      parameters:
        - name: page
          in: query
          description: The number of current page
          required: false
          type: string
        - name: limit
          in: query
          description: The limit number of ocurrences that must be showed per page
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UndefinedYetResponse"
    post:
      tags:
        - combos
      description: Submit an new Combo to the list
      operationId: combo
      parameters:
        - in: body
          name: postComboPayload
          description: Payload format to submit an new Combo
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
              foods:
                type: array
                items:
                  $ref: "#/definitions/partialFoodDefinition"
            example:
              name: "Burrito"
              foods:
                - name: "Burrito"
                  size: "M"
                  price: 5.13
                  refillable: false
                - name: "Taco"
                  size: "M"
                  price: 12.50
                  refillable: false
                - name: "Drink"
                  size: "M"
                  price: 5.13
                  refillable: false
                  image: "http://lorempixel.com/640/480/food"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UndefinedYetResponse"
        "400":
          description: BadRequest
          schema:
            $ref: "#/definitions/BadRequest"
  /combos/{comboId}:
    get:
      tags:
        - comboById
      description: Returns exclusive combo by id
      operationId: combo
      parameters:
        - name: comboId
          in: path
          required: true
          type: string
          description: ID of the current Combo
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/comboItem"
        "404":
          description: Resouce not found
          schema:
            $ref: "#/definitions/NotFound"
    put:
      tags:
        - comboById
      description: Edit informations from an specific Combo
      operationId: combo
      parameters:
        - name: comboId
          in: path
          required: true
          type: string
          description: ID of the current Combo
        - in: body
          name: putComboPayload
          description: Payload format to edit the current Combo
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
              foods:
                type: array
                items:
                  $ref: "#/definitions/partialFoodDefinition"
            example:
              name: "Burrito"
              foods:
                - name: "Burrito Put"
                  size: "M"
                  price: 6.13
                  refillable: false
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UndefinedYetResponse"
        "404":
          description: Resouce not found
          schema:
            $ref: "#/definitions/NotFound"
    patch:
      tags:
        - comboById
      description: Edit only one atribute from an specific Combo
      operationId: combo
      parameters:
        - name: comboId
          in: path
          required: true
          type: string
          description: ID of the current Combo
        - in: body
          name: patchComboPayload
          description: Payload format to edit the current Combo
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
              foods:
                type: array
                items:
                  $ref: "#/definitions/partialFoodDefinition"
            example:
              name: "Burrito Patched"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UndefinedYetResponse"
        "404":
          description: Resouce not found
          schema:
            $ref: "#/definitions/NotFound"
    delete:
      tags:
        - comboById
      description: Remove the specific combo from Combo List
      operationId: combo
      parameters:
        - name: comboId
          in: path
          required: true
          type: string
          description: ID of the current Combo
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/UndefinedYetResponse"
        "404":
          description: Resouce not found
          schema:
            $ref: "#/definitions/NotFound"
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  ingredientsDefinition:
    required:
      - name
      - isExpired
    properties:
      name:
        type: string
      isExpired:
        type: boolean
  partialFoodDefinition:
    required:
      - name
      - price
      - size
    properties:
      name:
        type: string
      price:
        type: number
      size:
        type: string
      refillable:
        type: boolean
      image:
        type: string
  foodItem:
    required:
      - name
      - price
      - size
      - drinkable
      - refillable
    properties:
      name:
        type: string
      price:
        type: number
      size:
        type: string
      drinkable:
        type: boolean
      refillable:
        type: boolean
      spicy:
        type: string
      image:
        type: string
      ingredients:
        type: array
        items:
          $ref: "#/definitions/ingredientsDefinition"
    example:
      name: "Food Example"
      price: 15.15
      size: "P"
      drinkable: false
      refillable: true
      spicy: "Hot"
      image: "http://lorempixel.com/640/480/food"
      ingredients:
        - name: "Lettuce"
          isExpired: false
        - name: "Carrot"
          isExpired: false
        - name: "Rice"
          isExpired: false
  comboItem:
    required:
      - name
    properties:
      name:
        type: string
      foods:
        type: array
        items:
          $ref: "#/definitions/partialFoodDefinition"
    example:
      name: "Combo Example"
      foods:
        - name: "Food One"
          price: 5.10
          size: "P"
          refillable: false
        - name: "Food Two"
          price: 5.20
          size: "Default"
          refillable: false
        - name: "Food Three"
          price: 5.30
          size: "M"
          refillable: false
      totalPrice: 15.60
  BadRequest:
    required:
      - results
    properties:
      results:
        type: object
        required:
          - status
          - message
        properties:
          status:
            type: string
          message:
            type: string
        example:
          status: 400
          message: Some explanation about what you did wrong :)
  NotFound:
    required:
      - results
    properties:
      results:
        type: object
        required:
          - status
          - message
        properties:
          status:
            type: string
          message:
            type: string
        example:
          status: 404
          message: Resource not found
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
